### ISSUE TITLE
space are deleted

### ISSUE THREAD

**Issue by Wildboy85** [Beej126/SingleInstanceAccumulator#1]
oops cannot delete
i tought space were deleted, but i added some "" around %1 in register base and it was ok

i use it for multiple robocopy, and to copy files and folders links in clipboard to send links to files and folders, and it is fantastic

**Comment by Beej126** [comment]
glad you found a way! glad you can use it! thanks for saying! 
![image](https://user-images.githubusercontent.com/6301228/49337614-cf9a6080-f5ca-11e8-8f93-62c3614271bc.png)
