### ISSUE TITLE
SingleInstanceAccumulator is passing invalid filenames if they contain special characters.

### ISSUE THREAD

**Issue by futuremotiondev** [Beej126/SingleInstanceAccumulator#10]
Snip

**Comment by Beej126** [comment]
@futuremotiondev - i've been dinking with this and there's hope... looks like it's a matter of using unicode oriented win32 apis versus the ansi version apis i've used so far ... just need a minute to pull it all together and i'll get you a new build out, hopefuly within next couple days... it's nice hearing it's useful to you... oh and way to go providing the repro, that makes anything way more conducive to engage

**Comment by futuremotiondev** [comment]
@Beej126 Awesome! Great to hear. Take your time, it's not mission critical or anything. Thanks again for all your work on this little gem of a tool.

**Comment by Beej126** [comment]
@futuremotiondev - [new build posted](https://github.com/Beej126/SingleInstanceAccumulator/releases/tag/v1.0.0.4), testing your files looks good to me, let me know

![image](https://github.com/Beej126/SingleInstanceAccumulator/assets/6301228/0da096f3-811d-4f3a-af77-538799ea1704)
