### ISSUE TITLE
Any possibility for a smaller executable? The version before v1.0.0.4 (tweaks to support unicode paths) was much smaller in filesize. 

### ISSUE THREAD

**Issue by futuremotiondev** [Beej126/SingleInstanceAccumulator#12]
Again, love the program and use it constantly. Only issue is that now the exe is above 100MB, and my scripts are taking much longer to launch due to the 100MB+ binary being loaded into memory much slower.

I'm assuming the latest version is statically compiled and includes all dependencies? Is there a way to create an executable without the included dependencies for those of us that already have runtimes installed? It would be a huge help as my scripts are definitely not as responsive as they used to be using the previous version.

Really appreciate all your hard work, and thanks for any consideration!

Jay

**Comment by Beej126** [comment]
always nice to hear! i just posted a non embedded build, only 14k, see if that works for you, see small notes over there on the release

**Comment by futuremotiondev** [comment]
You're awesome! I love you! :)
