### ISSUE TITLE
Where can I download the binary? (exe)

### ISSUE THREAD

**Issue by futuremotiondev** [Beej126/SingleInstanceAccumulator#2]
I really want to use this for a context menu, but I'm not a developer and don't really have a way to compile. Can you push the exe up into your repo?

**Comment by Beej126** [comment]
@cultmethod - sure, see [releases](https://github.com/Beej126/SingleInstanceAccumulator/releases)

**Comment by futuremotiondev** [comment]
I love you! Thank you so much. I was trying to build it in VSCode and failed miserably,

**Comment by Beej126** [comment]
@cultmethod - hope it works out for ya
