### ISSUE TITLE
Filenames with single quotes breaks functionality. 

### ISSUE THREAD

**Issue by futuremotiondev** [Beej126/SingleInstanceAccumulator#4]
I've successfully gotten this to work and I'm super excited! The only problem is that if a file with a single quote is passed through, everything breaks (assuming `-q:'` is set). Is there any chance in the world you can add an option to double up single quotes within files that are being passed?

For example:
`my_file'name.mov`

Should be transformed to:
`my_file''name.mov`

This change will get files with single quotes to parse correctly in Powershell.

**Comment by Beej126** [comment]
thanks for mentioning success... mainly for now just saying i've seen your request and it makes sense... i'll try to make the time to crack open project and do some tweak for this... in the interim, as "inspiration", could you give a taste of why you can't change filenames on your end? @visusys, just making sure you saw this?
