### ISSUE TITLE
The order of the files in the list

### ISSUE THREAD

**Issue by Graph-Man** [Beej126/SingleInstanceAccumulator#7]
Is it possible to make the files in the list follow in the order in which they were selected? 
Currently I select File1 and then File2, but they are listed as File2 and File1.

**Comment by Beej126** [comment]
i'm thinking that's how File Explorer feeds them in.
try playing with the order you select them in Explorer and particularly, which item you right mouse to invoke the context menu ... i've seen that one take precedence as the first... which makes some sense

**Comment by Graph-Man** [comment]
thanks
