### ISSUE TITLE
Why is the latest release over 140MB?!

### ISSUE THREAD

**Issue by futuremotiondev** [Beej126/SingleInstanceAccumulator#8]
The last release that I've been using is only `12kb`. What in God's name happened?

Also, what's changed with release three? Any notable differences?

Thanks for any info.

Jay

**Comment by Beej126** [comment]
i created a github action to auto compile and upload whenever code changes are committed... versus the first build i posted was a local build, manual upload ... i'm assuming the difference is i went with a self contained exe which brings in the whole dotnet framework so the user doesn't have to have that installed on their own... it's a classic tradeoff... it's not a priority for me but i'm assuming it'd be easy to tweak the build script to create both types.
